name: "Build-Android"

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Prepare NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip android-ndk-r27b-linux.zip
          ln -sf . jni

      - name: Build
        run: |
          ./android-ndk-r27b/ndk-build NDK_APP_ABI=${{ matrix.abi }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-android-${{ matrix.abi }}
          path: |
            libs/${{ matrix.abi }}/libhev-socks5-tunnel.so
            libs/${{ matrix.abi }}/hev-socks5-tunnel
          if-no-files-found: error
          retention-days: 7

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: "hev-*"
          merge-multiple: true

      - name: Upload artifacts to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in release/hev-*; do
            gh release upload ${{ github.event.release.tag_name }} $i
          done
