name: "Build-Android"

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Prepare NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip android-ndk-r27b-linux.zip
          ln -sf . jni

      - name: Build
        run: |
          ./android-ndk-r27b/ndk-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-android
          path: bin/
          if-no-files-found: error
          retention-days: 7

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: "hev-*"
          merge-multiple: true

      - name: Upload artifacts to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in release/hev-*; do
            gh release upload ${{ github.event.release.tag_name }} $i
          done
